const GAME_LEVELS = [
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                xxx             ",
    "                                                     xx    xx  xx!xx            ",
    "                                        o   o  xx              x!!!x            ",
    "                                                               xx!xx            ",
    "                                        xxxxx                   xvx             ",
    "                                                                             xx ",
    "  xx                                          o  o                            x ",
    "  x                      o                                                    x ",
    "  x                                          xxxxxx                         o x ",
    "  x               xxxx   o                                                    x ",
    "  x  @            x  x                                         xxxx           x ",
    "  xxxxxxxxxxxxxxxxx  xxxxxx  xxxxxxxx   xxxxxxxxxxxxxxx     xxxx  xxxxxxxxxxxxx ",
    "                                    x   x             x     x                   ",
    "                                    x!!!x             x!!!!!x                   ",
    "                                    x!!!x             x!!!!!x                   ",
    "                                    xxxxx             xxxxxxx                   ",
    "                                                                                ",
    "                                                                                ",
    ];