const GAME_LEVELS = [
[
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                xxx             ",
    "                                                     xx    xx  xx!xx            ",
    "                                        o   o  xx              x!!!x            ",
    "                                                               xx!xx            ",
    "                                        xxxxx                   xvx             ",
    "                                                                             xx ",
    "  x                                           o  o                            x ",
    "  x                      o                                                    x ",
    "  x               xxxx                       xxxxxx                         o x ",
    "  x               x  x   o                                                    x ",
    "  x  @            x  x                                         xxxx           x ",
    "  xxxxxxxxxxxxxxxxx  xxxxxx  xxxxxxxx   xxxxxxxxxxxxxxx     xxxx  xxxxxxxxxxxxx ",
    "                                    x   x             x     x                   ",
    "                                    x!!!x             x!!!!!x                   ",
    "                                    x!!!x             x!!!!!x                   ",
    "                                    xxxxx             xxxxxxx                   ",
    "                                                                                ",
    "                                                                                ",
    ], 
    [
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                xxx             ",
    "                                                     xx    xx  xx!xx            ",
    "                                        o   o  xx              x!!!x            ",
    "                                                               xx!xx            ",
    "  x                                     xxxxx                   xvx             ",
    "  x                                                                           x ",
    "  x                                           o  o                            x ",
    "  x               xxxx                                                        x ",
    "  x               xxxx                       xxxxxx                         o x ",
    "  x               xxxx                                                        x ",
    "  x   @           x  x                                         xxxx           x ",
    "  xxxxxxxxxx    xxx  xxx     xxxxxxxx   xxxxxxxxxxxxxxx     xxxx  xxxxxxxxxxxxx ",
    "                                    x   x             x     x                   ",
    "                                    x!!!x             x!!!!!x                   ",
    "                                    x!!!x             x!!!!!x                   ",
    "                                    xxxxx             xxxxxxx                   ",
    "                                                                                ",
    "                                                                                ",
    ]
];